universe=docker
docker_image = pangyuteng/ml:nnunetv2
docker_pull_policy = always

executable = run.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = log/$(cluster).$(process).out
error = log/$(cluster).$(process).err
log = log/$(cluster).$(process).log

request_cpus = 1
request_gpus = 1
request_memory = 24GB
request_disk = 1024MB
requirements = (OpSys == "LINUX" && Arch == "X86_64" && GPUMEM > 12000)
+DevShmSize = 8589934592

arguments = "hello nnunet"
queue

